const statusEl = document.getElementById('status');
const authorizeButton = document.getElementById('authorize');

function setStatus(message) {
  statusEl.textContent = message;
}

function executeInActiveTab(func) {
  return new Promise((resolve, reject) => {
    chrome.tabs.query({ active: true, currentWindow: true }, tabs => {
      const tab = tabs[0];
      if (!tab?.id) {
        reject(new Error('No active tab found.'));
        return;
      }
      chrome.scripting.executeScript(
        {
          target: { tabId: tab.id },
          func,
        },
        results => {
          const err = chrome.runtime.lastError;
          if (err) {
            reject(new Error(err.message));
            return;
          }
          resolve(results?.[0]?.result);
        },
      );
    });
  });
}

function getYoutubeCookies(url) {
  return new Promise((resolve, reject) => {
    chrome.cookies.getAll({ url }, cookies => {
      const err = chrome.runtime.lastError;
      if (err) {
        reject(new Error(err.message));
        return;
      }
      resolve(cookies || []);
    });
  });
}

function cookieKey(cookie) {
  return `${cookie.domain}\n${cookie.path}\n${cookie.name}`;
}

function toNetscapeCookies(cookies) {
  const lines = [
    '# Netscape HTTP Cookie File',
    '# Generated by MeTube Cookie Helper.',
  ];
  for (const cookie of cookies) {
    const httpOnlyPrefix = cookie.httpOnly ? '#HttpOnly_' : '';
    const domain = `${httpOnlyPrefix}${cookie.domain}`;
    const includeSubdomains = cookie.domain.startsWith('.') ? 'TRUE' : 'FALSE';
    const path = cookie.path || '/';
    const secure = cookie.secure ? 'TRUE' : 'FALSE';
    const expires = cookie.session ? '0' : String(Math.floor(cookie.expirationDate || 0));
    lines.push([
      domain,
      includeSubdomains,
      path,
      secure,
      expires,
      cookie.name,
      cookie.value,
    ].join('\t'));
  }
  return `${lines.join('\n')}\n`;
}

async function getMeTubeSessionInfo() {
  return executeInActiveTab(() => {
    const profile = localStorage.getItem('metube_cookie_profile');
    return {
      href: location.href,
      uploadUrl: new URL('upload-cookies', location.href).href,
      profile,
    };
  });
}

async function collectYoutubeCookies() {
  const urls = [
    'https://www.youtube.com/',
    'https://youtube.com/',
    'https://m.youtube.com/',
  ];
  const byKey = new Map();
  for (const url of urls) {
    const cookies = await getYoutubeCookies(url);
    for (const cookie of cookies) {
      byKey.set(cookieKey(cookie), cookie);
    }
  }
  return [...byKey.values()];
}

async function uploadCookies(uploadUrl, profile, cookiesText) {
  const body = new FormData();
  body.append('cookies', new Blob([cookiesText], { type: 'text/plain' }), 'cookies.txt');
  body.append('cookie_profile', profile);
  const response = await fetch(uploadUrl, {
    method: 'POST',
    body,
    credentials: 'include',
  });
  const text = await response.text();
  let payload;
  try {
    payload = JSON.parse(text);
  } catch {
    payload = { status: response.ok ? 'ok' : 'error', msg: text };
  }
  if (!response.ok || payload.status !== 'ok') {
    throw new Error(payload.msg || `Upload failed with HTTP ${response.status}`);
  }
  return payload;
}

authorizeButton.addEventListener('click', async () => {
  authorizeButton.disabled = true;
  setStatus('Reading MeTube session...');
  try {
    const session = await getMeTubeSessionInfo();
    if (!session?.profile) {
      throw new Error('This tab does not look like a MeTube page with an active session profile.');
    }
    setStatus('Reading YouTube cookies...');
    const cookies = await collectYoutubeCookies();
    if (!cookies.length) {
      throw new Error('No YouTube cookies found in this browser profile.');
    }
    setStatus('Authorizing this MeTube session...');
    await uploadCookies(session.uploadUrl, session.profile, toNetscapeCookies(cookies));
    setStatus(`Authorized ${cookies.length} YouTube cookies for this MeTube session.`);
  } catch (err) {
    setStatus(err?.message || 'Authorization failed.');
  } finally {
    authorizeButton.disabled = false;
  }
});
